### ISSUE TITLE
Doesn't conform to the spec

### ISSUE THREAD

**Issue by chocolateboy** [dracupid/ispromise#1]
A function can be a promise:

> “promise” is an object **or function** with a then method
> whose behavior conforms to this specification. [1]

but the [current implementation](https://github.com/dracupid/ispromise/blob/5f0c8395835ad378f8bafbc1cde67fd91c81b828/index.js) only checks for `object`.

[1] https://promisesaplus.com/#terminology

**Comment by dracupid** [comment]
Thx for pointing out it. 😄
